//! Embeds every rules/**/*.json (except ruleset.json) at compile time
//! (spec §6.5). Std-only; a forgotten or orphaned rule fails the 1:1 test in
//! tests/embedding.rs, not review attention.
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let rules_dir = manifest.join("../../rules");
    println!("cargo::rerun-if-changed={}", rules_dir.display());

    let mut rule_files = Vec::new();
    collect_json(&rules_dir, &rules_dir, &mut rule_files);
    rule_files.sort();

    let mut generated = String::from(
        "/// (relative path under rules/, file contents) — generated by build.rs.\n\
         pub const EMBEDDED_RULES: &[(&str, &str)] = &[\n",
    );
    for relative in &rule_files {
        let absolute = rules_dir.join(relative);
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            relative,
            absolute.display()
        ));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("embedded_rules.rs"), generated).unwrap();
}

fn collect_json(root: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in std::fs::read_dir(dir).expect("rules directory is readable") {
        let path = entry.expect("rules entry is readable").path();
        if path.is_dir() {
            collect_json(root, &path, out);
        } else if path.extension().is_some_and(|ext| ext == "json")
            && path.file_name().is_some_and(|name| name != "ruleset.json")
        {
            let relative = path
                .strip_prefix(root)
                .unwrap()
                .components()
                .map(|component| component.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            out.push(relative);
        }
    }
}
